name: Branches Workflow
on:
  push:
    branches:
      - '**'
      - '!master'
jobs:
  build-debug-apk:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Build APK
        run: ./gradlew --no-daemon assembleDebug
      - name: Print APK info
        run: cat app/build/outputs/apk/debug/output-metadata.json
      - name: Export APK
        uses: actions/upload-artifact@v7
        with:
          name: darsadyar-apk
          path: app/build/outputs/apk/debug/app-debug.apk
